"""create rents table

Revision ID: bdd9aab98323
Revises: 9127e4ae25d7
Create Date: 2026-07-17 03:09:42.254872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd9aab98323'
down_revision: Union[str, Sequence[str], None] = '9127e4ae25d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', name='itemcondition'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'ACTIVE_LOAN', 'MAINTENANCE', 'HIDDEN', name='itemstatus'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_table('rents',
    sa.Column('from_userid', sa.String(), nullable=False),
    sa.Column('to_userid', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('rent_time', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('total_charge', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rents_asset_id'), 'rents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rents_from_userid'), 'rents', ['from_userid'], unique=False)
    op.create_index(op.f('ix_rents_to_userid'), 'rents', ['to_userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rents_to_userid'), table_name='rents')
    op.drop_index(op.f('ix_rents_from_userid'), table_name='rents')
    op.drop_index(op.f('ix_rents_asset_id'), table_name='rents')
    op.drop_table('rents')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
